"""add search_type to search_history

Revision ID: 0f81f848f3e0
Revises: e31ce67e1914
Create Date: 2026-06-19 11:08:40.825645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f81f848f3e0'
down_revision: Union[str, Sequence[str], None] = 'e31ce67e1914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('search_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'search_type')
    # ### end Alembic commands ###
